### PR TITLE
Feat/add absorb

### PR DESCRIPTION
**Pull request by Isa0801**

### CODE REVIEW

**Comment by Isa0801** [comment]
[Add ability to absorb/eat enemies](https://trello.com/c/I4bQ17m6/9-add-ability-to-absorb-eat-enemies)

**Comment by Lemorz56** [comment]
LGTM 😄 🎆

**Comment by Lemorz56** [comment]
@Isa0801 I pushed a branch named "feat/devtools" (I could not come up with a better name atm since its actually not devtools just spawning food lol) where i just added that once i click there is a food spawned (buggy) but just for testing the absorb :D Works good nice work

**Comment by Isa0801** [comment]
@Lemorz56 I think the name fits tbh, because it is tool that we use to spawn the food for testing (I played around with it is fun :D ). I think the buggy part is due to that Absorbable Objects class overwrites scale (I think). Nice work to us :D, we did a good work :).

**Comment by Isa0801** [comment]
@Lemorz56 I think the name fits tbh, because it is tool that we use to spawn the food for testing (I played around with it is fun :D ). I think the buggy part is due to that Absorbable Objects class overwrites scale (I think). Nice work to us :D, we did a good work :).

**Review by Lemorz56 — COMMENTED** [review]
looks good (just testing github from the phone)

**Pull request merged**
